// export enum StoreGroupsEnum {
// 	SOLO,
// 	GROUP,
// 	STAFF,
// 	TRAINEE,
// 	ACTING,
// 	MODEL,
// }

// export const DEFAULT_STORE_GROUP_TABS: StoryByGroupTabs[] = [
// 	{
// 		title: 'Solistes',
// 		id: StoreGroupsEnum.SOLO,
// 	},
// 	{
// 		title: 'Trainees',
// 		id: StoreGroupsEnum.TRAINEE,
// 	},
// 	{
// 		title: 'Staffs',
// 		id: StoreGroupsEnum.STAFF,
// 	},
// 	{
// 		title: 'Acteurs',
// 		id: StoreGroupsEnum.ACTING,
// 	},
// 	{
// 		title: 'Influenceur, models & sportifs',
// 		id: StoreGroupsEnum.MODEL,
// 	},
// ]

// export const GROUP_STORE_TABS: StoryByGroupTabs = {
// 	title: 'Groupes',
// 	id: StoreGroupsEnum.GROUP,
// }

// export enum StoreSectionEnum {
// 	COMEBACK,
// 	PROMOTE,
// 	PROMOTE_PROJECT,
// 	BOOSTER,
// 	PROJECT,
// 	GOODIES,
// 	CONTENT,
// 	SPECIFIC,
// }

// export const DEFAULT_STORE_GROUP: StoreByGroup = {
// 	title: 'Boutique groupe',
// 	id: StoreGroupsEnum.GROUP,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.COMEBACK,
// 			title: 'Réaliser un comeback',
// 			description:
// 				"les solos purs, réalisés en dehors d’une activité de groupe (ex. il ne s'agit pas d'intro. de membre ou d'era ni d'outro du groupe), doivent obligatoirement être fait par des personnages ayant au minimum le niveau 8.",
// 			items: [
// 				{ id: 1, name: 'single', isBooster: false, gain: 14, price: 140, condition: '' },
// 				{ id: 2, name: 'commercial mv (single)', isBooster: false, condition: '', price: 240, gain: 24 },
// 				{ id: 3, name: 'mini album (2 à 4 chansons)', isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 4, name: 'mini album (5 à 7 chansons)', isBooster: false, condition: '', price: 240, gain: 24 },
// 				{ id: 5, name: 'full album (8 à 12 chansons)', isBooster: false, condition: '', price: 340, gain: 34 },
// 				{
// 					id: 6,
// 					name: 'repack album',
// 					isBooster: false,
// 					condition: 'max 10 nouvelles chansons + min 3 chansons déjà sorties.',
// 					price: 280,
// 					gain: 28,
// 				},
// 				{
// 					id: 7,
// 					name: 'double release',
// 					isBooster: false,
// 					condition: 'sortie comprenant deux mvs (ex. blackpink whistle & boombayah sortie en même temps).',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{
// 					id: 8,
// 					name: "conversion jpn ou chn d'un single kr",
// 					bonusStatus: [AgenciesEnum.XY],
// 					isBooster: false,
// 					condition: 'item possible si le groupe a release la version kr 6 mois auparavant minimum.',
// 					price: 120,
// 					gain: 12,
// 				},
// 				{
// 					id: 9,
// 					name: 'single jpn ou chn',
// 					bonusStatus: [AgenciesEnum.XY],
// 					isBooster: false,
// 					condition: 'chinois, japonais ; palier 7, xingyuan music : palier 5',
// 					price: 180,
// 					gain: 18,
// 				},
// 				{
// 					id: 10,
// 					name: 'single anglais',
// 					isBooster: false,
// 					condition: 'palier 9 pour la moitié du groupe au moins.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 11, name: 'featuring', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 12, name: 'collaboration', isBooster: false, condition: '', price: 120, gain: 12 },
// 				{ id: 1, name: 'single', isBooster: false, gain: 10, price: 100, condition: '' },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROMOTE,
// 			title: 'Promotion Générale',
// 			description: '',
// 			items: [
// 				{
// 					id: 14,
// 					name: 'expérience',
// 					isBooster: false,
// 					condition: 'achat limité à 10 quantités par mois.',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{ id: 15, name: 'faire une dance practice', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 16,
// 					name: 'photoshoot',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 17,
// 					name: 'couverture de magazine (3★)',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: "l'item doit être cumulé avec l'item photoshoot.",
// 					price: 60,
// 					gain: 6,
// 				},
// 				{ id: 18, name: 'interview magazine', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 19, name: 'interview vidéo (ex. elle)', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 20,
// 					name: 'commercials',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 21,
// 					name: 'bonus égérie: participer à un photoshoot / cf',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 5,
// 				},
// 				{ id: 22, name: "face d'une marque kr (2★)", isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 23, name: "face d'une marque inter (3★)", isBooster: false, condition: '', price: 250, gain: 25 },
// 				{ id: 24, name: "ambassadeur d'une marque kr (3★)", isBooster: false, condition: '', price: 360, gain: 36 },
// 				{
// 					id: 25,
// 					name: "ambassadeur d'une marque internationale (4★)",
// 					isBooster: false,
// 					condition: '',
// 					price: 600,
// 					gain: 60,
// 				},
// 				{ id: 26, name: 'réaliser des campagnes publicitaires', isBooster: false, price: 200, gain: 20 },
// 				{
// 					id: 27,
// 					name: 'bonus égérie: post sur les réseaux en partenariat avec une marque',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 5,
// 				},
// 				{
// 					id: 28,
// 					name: "être mc d'une émission",
// 					bonusStatus: [AgenciesEnum.MC],
// 					isBooster: false,
// 					condition: 'avoir obligatoirement le skill variety show & le palier 7.',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 29,
// 					name: "faire partie du casting d'une émission",
// 					isBooster: false,
// 					condition: 'cet item est pour les apparitions à longue durée type sea of hope etc...',
// 					price: 300,
// 					gain: 30,
// 				},
// 				{ id: 30, name: 'apparition dans une émission', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 31,
// 					name: 'bonus skill face: émission',
// 					isBooster: false,
// 					condition: "s'achète EN PLUS de l'item apparition dans une émission.",
// 					price: 0,
// 					gain: 5,
// 				},
// 				{
// 					id: 32,
// 					name: "être mc d'un music show",
// 					isBooster: false,
// 					condition:
// 						"palier 6. pour savoir si une place est libre actuellement, merci d'aller vérifier dans le sujet MY!CUE & GEUMSORI (+ les conditions).",
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 33,
// 					name: 'avoir son talk show (radio)',
// 					isBooster: false,
// 					condition:
// 						'palier 9. cet item s’achète une fois pour le talk show en question. si vous souhaitez y ajouter une nouvelle saison, il faudra acheter l’année suivant l’item nouvelle saison.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 34, name: 'nouvelle saison talk show', isBooster: false, condition: 'palier 9.', price: 120, gain: 12 },
// 				{ id: 35, name: 'participer à un radio show', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{ id: 36, name: 'apparaître dans un m/v', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 37, name: 'youtube (1 mois)', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 38,
// 					name: 'youtube (15jrs)',
// 					isBooster: false,
// 					condition: "ne peut s'acheter qu'après l'achat de l'item youtube (1 mois)",
// 					price: 110,
// 					gain: 11,
// 				},
// 				{ id: 39, name: 'bonus gnation: poster sur youtube', isBooster: false, condition: '', price: 0, gain: 4 },
// 				{ id: 40, name: 'faire certifier ses réseaux', isBooster: false, condition: '', price: 100, gain: 10 },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.BOOSTER,
// 			title: 'boosters',
// 			description:
// 				'pour rappel, la moitié minimum du groupe doit acheter des boosters (par exemple 2/4 ou 3/5) et celles et ceux achetant les items doivent en prendre un nombre égal (sans que ça soit les mêmes).',
// 			items: [
// 				{ id: 41, name: 'réaliser des teasers pour son cb', isBooster: true, price: 100, gain: 6000 },
// 				{ id: 42, name: 'vlive countdown', isBooster: true, condition: '', price: 300, gain: 18000 },
// 				{
// 					id: 43,
// 					name: 'fans meetings',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu'à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{ id: 44, name: 'instagram live promotionnel', isBooster: true, condition: '', price: 100, gain: 6000 },
// 				{ id: 45, name: 'showcase', isBooster: true, condition: '', price: 150, gain: 9000 },
// 				{
// 					id: 46,
// 					name: 'promotions (studio choom, relay dance, live…)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu'à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 47,
// 					name: 'inscription music show (petit budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes s’inscrivant aux musics shows avec un petit budget ne font, en général, pas les 4 semaines de promotions. sinon, leur temps d’antenne diminue au fil des semaines.',
// 					price: 100,
// 					gain: 6000,
// 				},
// 				{
// 					id: 48,
// 					name: 'inscription music show (gros budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes avec un gros budget de promotions réalisent leurs 4 semaines et performent l’intégralité des chansons.',
// 					price: 200,
// 					gain: 12000,
// 				},
// 				{
// 					id: 49,
// 					name: 'radio',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 50,
// 					name: 'promotion télévisé (weekly idoles...)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu'à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 51,
// 					name: 'affiches promotionnelles station métro/bus',
// 					isBooster: true,
// 					condition: '',
// 					price: 200,
// 					gain: 12000,
// 				},
// 				{
// 					id: 52,
// 					name: 'affiches promotionnelles coex kpop square (2★)',
// 					isBooster: true,
// 					condition: '',
// 					price: 300,
// 					gain: 18000,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: 'Réalisation de projets',
// 			description:
// 				'les items de production sont à prendre occasionnellement (3 fois/mois si lié au projet d’un tier) ; gardez en tête que les idoles n’ont pas beaucoup de temps à consacrer à d’autres productions/réalisations que les leurs. de ce fait, favorisez l’auto-prod.',
// 			items: [
// 				{
// 					id: 53,
// 					name: 'production d’une tt (crédité)',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: 'composition, production, arrangement, paroles, beats.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 54,
// 					name: 'production d’une tt (non crédité)',
// 					isBooster: false,
// 					condition: 'forcément associé à de la co-production, cet item n’apporte du coup pas de streams.',
// 					price: 70,
// 					gain: 7,
// 				},
// 				{
// 					id: 55,
// 					name: 'production d’une b-side',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 70,
// 					gain: 7,
// 				},
// 				{
// 					id: 56,
// 					name: 'production 3 b-sides',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 210,
// 					gain: 25,
// 				},
// 				{ id: 57, name: 'production d’une ost', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 58,
// 					name: "participer à la chorégraphie d'une émission",
// 					isBooster: false,
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{ id: 59, name: 'chorégraphie', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{ id: 60, name: 'direction artistique', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 61,
// 					name: '2nd rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 62,
// 					name: 'lead rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{
// 					id: 63,
// 					name: '2nd rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 64,
// 					name: 'lead rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 260,
// 					gain: 26,
// 				},
// 				{
// 					id: 65,
// 					name: 'caméo (drama ou film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 80,
// 					gain: 8,
// 				},
// 				{ id: 66, name: 'participer à un masterclass (1jr)', isBooster: false, condition: '', price: 120, gain: 12 },
// 				{
// 					id: 67,
// 					name: 'participer à un séminaire (2 à 3 jrs)',
// 					isBooster: false,
// 					condition: '',
// 					price: 240,
// 					gain: 24,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.GOODIES,
// 			title: 'vente de goodies/projets fan',
// 			description:
// 				'il faut rester réaliste dans l’achat des items suivants. les albums s’achètent uniquement dans le cas d’une release, les albums concerts suite à un concert, season’s greetings une fois par un (au début d’année) etc…',
// 			items: [
// 				{ id: 68, name: 'album physique (simple)', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 69, name: 'album physique (différentes versions)', isBooster: false, condition: '', price: 70, gain: 7 },
// 				{ id: 70, name: 'album physique (members versions)', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 71, name: 'photobook & concert dvd', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 72, name: 'photobook', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 73, name: 'season’s greetings', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 74,
// 					name: 'official fanclub membership',
// 					isBooster: false,
// 					condition: 'achat possible une fois tous les 6 mois.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 75, name: 'lightstick', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 76, name: 'goodies divers', isBooster: false, condition: '', price: 220, gain: 22 },
// 				{ id: 77, name: 'vlive solo', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 78, name: 'vlive groupe', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 79, name: 'vlive anniversaire', isBooster: false, condition: '', price: 200, gain: 20 },
// 				{
// 					id: 80,
// 					name: 'affiches anniversaire',
// 					isBooster: false,
// 					condition:
// 						"s'achète pour l'anniversaire de l'artiste, mais également pour l'anniversaire des débuts de l'artiste.",
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 81, name: 'coffee event (anniversaire ou cb)', isBooster: false, condition: '', price: 150, gain: 15 },
// 				{ id: 82, name: 'envoi food truck', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 83,
// 					name: 'organiser un concert (corée)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 				},
// 				{
// 					id: 84,
// 					name: 'organiser un fancon',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 190,
// 					gain: 19,
// 				},
// 				{
// 					id: 85,
// 					name: 'participer à un festival',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition:
// 						"les festivals sont considérés comme une tournée qu'à partir de 5 dates sur un même pays/continent.",
// 					price: 150,
// 					gain: 15,
// 				},
// 				{
// 					id: 86,
// 					name: 'tournée de concerts/festivals (asie)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{
// 					id: 87,
// 					name: 'tournée de concerts/festivals (us & eu)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: 'palier 7.',
// 					price: 400,
// 					gain: 40,
// 				},
// 				{
// 					id: 88,
// 					name: 'tournée mondiale',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 600,
// 					gain: 60,
// 				},
// 				{
// 					id: 89,
// 					name: "participer au concert d'un artiste",
// 					isBooster: false,
// 					condition: 'attention, si ton personnage y participe sans son groupe, il doit avoir 4 étoiles en solo.',
// 					price: 160,
// 					gain: 16,
// 				},
// 			],
// 		},
// 	],
// }

// export const DEFAULT_STORE_STAFF: StoreByGroup = {
// 	title: 'Boutique staff',
// 	id: StoreGroupsEnum.STAFF,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.CONTENT,
// 			title: 'Élaboration de contenu',
// 			description: '',
// 			items: [
// 				{ id: 14, name: 'expérience', isBooster: false, price: 100, gain: 10, condition: '' },
// 				{ id: 37, name: 'youtube (1 mois)', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 38,
// 					name: 'youtube (15jrs)',
// 					isBooster: false,
// 					condition: "ne peut s'acheter qu'après l'achat de l'item youtube (1 mois).",
// 					price: 110,
// 					gain: 11,
// 				},
// 				{ id: 99, name: 'ouvrir son insta officiel', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 40, name: 'faire certifier ses réseaux', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{
// 					id: 28,
// 					name: "être mc d'une émission",
// 					bonusStatus: [AgenciesEnum.MC],
// 					isBooster: false,
// 					condition: 'voir les émissions et les rôles possibles pour un staff.',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{
// 					id: 29,
// 					name: "faire partie du casting d'une émission",
// 					isBooster: false,
// 					condition: 'cet item est pour les apparitions à longue durée type sea of hope ou gtc.',
// 					price: 200,
// 					gain: 20,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: 'Élaboration de projets',
// 			description: '',
// 			items: [
// 				{
// 					id: 53,
// 					name: 'production d’une tt (crédité)',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 				},
// 				{ id: 54, name: 'production d’une tt (non crédité)', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{
// 					id: 55,
// 					name: 'production d’une b-side',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{
// 					id: 56,
// 					name: 'production 3 b-sides',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 180,
// 					gain: 18,
// 				},
// 				{ id: 57, name: 'production d’une ost', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{ id: 191, name: 'backdance', isBooster: false, price: 50, gain: 5, condition: '' },
// 				{ id: 148, name: 'réaliser un photoshoot', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 60,
// 					name: 'direction artistique',
// 					isBooster: false,
// 					condition: 'peut être lié à un comeback, un shooting ou un cf.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 150, name: 'stylisme', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{ id: 151, name: 'make-up artist', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 152,
// 					name: "participation à la réalisation d'un mv",
// 					isBooster: false,
// 					condition: 'réalisation, montage, éditing, etc.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 153,
// 					name: "participation à la réalisation d'un drama",
// 					isBooster: false,
// 					condition: 'réalisation, montage, éditing, etc.',
// 					price: 340,
// 					gain: 34,
// 				},
// 				{
// 					id: 154,
// 					name: "participation à la réalisation d'un film",
// 					isBooster: false,
// 					condition: 'réalisation, scénario, éditing, etc. possible 2 fois par an.',
// 					price: 400,
// 					gain: 40,
// 				},
// 				{ id: 155, name: "participer au graphisme d'un album", isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 156,
// 					name: 'avoir la mention (prod. by x) sur un cb',
// 					isBooster: false,
// 					condition:
// 						'min. 3 étoiles. achat possible uniquement par les producteurs et doit être discuté avec l’intéressé au préalable.',
// 					price: 0,
// 					gain: 0,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.SPECIFIC,
// 			title: 'item spécifiques',
// 			description: '',
// 			items: [
// 				{
// 					id: 157,
// 					name: 'offrir des vacances à son artiste ou groupe',
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 158,
// 					name: 'avoir un van de taille normal (5 places)',
// 					isBooster: false,
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 159,
// 					name: 'avoir un van luxueux (8 places)',
// 					isBooster: false,
// 					condition: '',
// 					price: 220,
// 					gain: 22,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 160,
// 					name: 'avoir un stagiaire (pendant un mois)',
// 					isBooster: false,
// 					condition: '',
// 					price: 180,
// 					gain: 18,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 161,
// 					name: 'louer un dortoir de taille normale',
// 					isBooster: false,
// 					condition: '',
// 					price: 250,
// 					gain: 25,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 162,
// 					name: 'louer un dortoir de grande taille',
// 					isBooster: false,
// 					condition: '',
// 					price: 310,
// 					gain: 31,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 163,
// 					name: 'louer un dortoir de luxe',
// 					isBooster: false,
// 					condition: 'groupe/artiste min. 4 étoiles',
// 					price: 450,
// 					gain: 45,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 164,
// 					name: 'louer des appartements séparés',
// 					isBooster: false,
// 					condition: 'groupe/artiste min. 5 étoiles.',
// 					price: 450,
// 					gain: 45,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 84,
// 					name: 'organiser un fancon',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 70,
// 					gain: 7,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 83,
// 					name: 'organiser un concert (corée)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 86,
// 					name: 'tournée de concerts/festivals (asie)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 300,
// 					gain: 30,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 87,
// 					name: 'tournée de concerts/festivals (us & eu)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: 'palier 8.',
// 					price: 400,
// 					gain: 40,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 88,
// 					name: 'tournée mondiale',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: 'palier 9.',
// 					price: 600,
// 					gain: 60,
// 					specificITem: 2,
// 				},
// 				{
// 					id: 41,
// 					name: 'réaliser des teasers pour son cb',
// 					isBooster: true,
// 					condition: '',
// 					price: 100,
// 					gain: 6000,
// 					specificITem: 2,
// 					doubleGain: 10,
// 				},
// 				{
// 					id: 42,
// 					name: 'vlive countdown',
// 					isBooster: true,
// 					condition: '',
// 					price: 300,
// 					gain: 18000,
// 					specificITem: 2,
// 					doubleGain: 30,
// 				},
// 				{
// 					id: 43,
// 					name: 'fans meetings',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu'à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 					specificITem: 2,
// 					doubleGain: 50,
// 				},
// 				{
// 					id: 44,
// 					name: 'instagram live promotionnel',
// 					isBooster: true,
// 					condition: '',
// 					price: 100,
// 					gain: 6000,
// 					specificITem: 2,
// 					doubleGain: 10,
// 				},
// 				{
// 					id: 45,
// 					name: 'showcase',
// 					isBooster: true,
// 					condition: '',
// 					price: 150,
// 					gain: 9000,
// 					specificITem: 2,
// 					doubleGain: 15,
// 				},
// 				{
// 					id: 46,
// 					name: 'promotions (studio choom, relay dance, live…)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 					specificITem: 2,
// 					doubleGain: 5,
// 				},
// 				{
// 					id: 47,
// 					name: 'inscription music show (petit budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes s’inscrivant aux musics shows avec un petit budget ne font, en général, pas les 4 semaines de promotions. sinon, leur temps d’antenne diminue au fil des semaines.',
// 					price: 100,
// 					gain: 6000,
// 					specificITem: 2,
// 					doubleGain: 10,
// 				},
// 				{
// 					id: 48,
// 					name: 'inscription music show (gros budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes avec un gros budget de promotions réalisent leurs 4 semaines et performent l’intégralité des chansons.',
// 					price: 200,
// 					gain: 3000,
// 					specificITem: 2,
// 					doubleGain: 20,
// 				},
// 				{
// 					id: 49,
// 					name: 'radio',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 					specificITem: 2,
// 					doubleGain: 5,
// 				},
// 				{
// 					id: 50,
// 					name: 'promotion télévisé (weekly idoles...)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 					specificITem: 2,
// 					doubleGain: 5,
// 				},
// 				{
// 					id: 51,
// 					name: 'affiches promotionnelles station métro/bus',
// 					isBooster: true,
// 					condition: '',
// 					price: 200,
// 					gain: 12000,
// 					specificITem: 2,
// 					doubleGain: 20,
// 				},
// 				{
// 					id: 52,
// 					name: 'affiches promotionnelles coex kpop square (2★)',
// 					isBooster: true,
// 					condition: '',
// 					price: 300,
// 					gain: 18000,
// 					specificITem: 3,
// 					doubleGain: 30,
// 				},
// 				{
// 					id: 165,
// 					name: 'ouvrir son studio photo',
// 					isBooster: false,
// 					condition: '',
// 					price: 300,
// 					gain: 30,
// 					specificITem: 3,
// 				},
// 				{
// 					id: 166,
// 					name: 'sortir un photobook',
// 					isBooster: false,
// 					condition: '',
// 					price: 120,
// 					gain: 12,
// 					specificITem: 3,
// 				},
// 				{
// 					id: 167,
// 					name: 'organiser une exposition',
// 					isBooster: false,
// 					condition: '',
// 					price: 400,
// 					gain: 40,
// 					specificITem: 3,
// 				},
// 				{
// 					id: 168,
// 					name: 'réaliser une masterclass',
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 3,
// 				},
// 				{
// 					id: 169,
// 					name: 'réaliser un reportage',
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 3,
// 				},
// 				{
// 					id: 170,
// 					name: 'réaliser un programme remise en forme',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 					specificITem: 4,
// 				},
// 				{
// 					id: 171,
// 					name: "participer à l'entraînement post comeback",
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 					specificITem: 4,
// 				},
// 				{
// 					id: 172,
// 					name: 'devenir coach personnel d’un artiste',
// 					isBooster: false,
// 					condition: "préciser le nom de l'artiste.",
// 					price: 400,
// 					gain: 40,
// 					specificITem: 4,
// 				},
// 				{ id: 173, name: 'lancer sa marque', isBooster: false, condition: '', price: 300, gain: 30, specificITem: 5 },
// 				{
// 					id: 174,
// 					name: 'bosser pour une marque',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 					specificITem: 5,
// 				},
// 				{
// 					id: 175,
// 					name: 'créer une gamme en collaboration',
// 					isBooster: false,
// 					condition: '',
// 					price: 120,
// 					gain: 12,
// 					specificITem: 5,
// 				},
// 				{
// 					id: 176,
// 					name: 'influencer une tendance',
// 					isBooster: false,
// 					condition: '',
// 					price: 160,
// 					gain: 16,
// 					specificITem: 5,
// 				},
// 				{ id: 177, name: 'ouvrir sa boutique', isBooster: false, condition: '', price: 300, gain: 30, specificITem: 5 },
// 				{
// 					id: 178,
// 					name: 'participer à la fashion week',
// 					isBooster: false,
// 					condition: '',
// 					price: 400,
// 					gain: 40,
// 					specificITem: 5,
// 				},
// 				{
// 					id: 179,
// 					name: 'devenir le styliste/make-up officiel d’un artiste',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 					specificITem: 5,
// 				},
// 				{
// 					id: 180,
// 					name: "devenir chorégraphe d'un studio",
// 					isBooster: false,
// 					condition: '',
// 					price: 300,
// 					gain: 30,
// 					specificITem: 6,
// 				},
// 				{
// 					id: 181,
// 					name: "participer à la chorégraphie d'un stage",
// 					isBooster: false,
// 					condition: '',
// 					price: 190,
// 					gain: 19,
// 					specificITem: 6,
// 				},
// 				{
// 					id: 182,
// 					name: 'chorégraphie (cb ou vidéo ytb)',
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 					specificITem: 6,
// 				},
// 				{
// 					id: 183,
// 					name: 'chorégraphie (non crédité)',
// 					isBooster: false,
// 					condition: '',
// 					price: 70,
// 					gain: 7,
// 					specificITem: 6,
// 				},
// 				{ id: 184, name: 'ouvrir son studio de danse', isBooster: false, price: 500, gain: 50, specificITem: 6 },
// 				{
// 					id: 185,
// 					name: 'gérer une masterclass',
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 6,
// 				},
// 				{ id: 186, name: 'gérer un séminaire', isBooster: false, condition: '', price: 220, gain: 22, specificITem: 6 },
// 				{ id: 187, name: 'gérer un bootcamp', isBooster: false, condition: '', price: 350, gain: 35, specificITem: 6 },
// 				{
// 					id: 188,
// 					name: 'bosser officiellement pour une agence',
// 					isBooster: false,
// 					condition: '',
// 					price: 500,
// 					gain: 50,
// 					specificITem: 6,
// 				},
// 				{
// 					id: 189,
// 					name: 'apparaître dans un mv (danseur·euse)',
// 					isBooster: false,
// 					condition: "ø backdance mais d'une figuration chorégraphié.",
// 					price: 100,
// 					gain: 10,
// 					specificITem: 6,
// 				},
// 				{
// 					id: 190,
// 					name: 'commercial cf danse',
// 					isBooster: false,
// 					condition: '1/an & niveau 9',
// 					price: 240,
// 					gain: 24,
// 					specificITem: 6,
// 				},
// 			],
// 		},
// 	],
// }

// export const DEFAULT_STORE_SOLO: StoreByGroup = {
// 	title: 'Boutique soliste',
// 	id: StoreGroupsEnum.SOLO,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.COMEBACK,
// 			title: 'Réaliser un comeback',
// 			description: '',
// 			items: [
// 				{ id: 1, name: 'single', isBooster: false, gain: 14, price: 140, condition: '' },
// 				{ id: 2, name: 'commercial mv (single)', isBooster: false, condition: '', price: 240, gain: 24 },
// 				{ id: 3, name: 'mini album (2 à 4 chansons)', isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 4, name: 'mini album (5 à 7 chansons)', isBooster: false, condition: '', price: 240, gain: 24 },
// 				{ id: 5, name: 'full album (8 à 12 chansons)', isBooster: false, condition: '', price: 340, gain: 34 },
// 				{
// 					id: 6,
// 					name: 'repack album',
// 					isBooster: false,
// 					condition: 'max 10 nouvelles chansons + min 3 chansons déjà sorties.',
// 					price: 280,
// 					gain: 28,
// 				},
// 				{
// 					id: 7,
// 					name: 'double release',
// 					isBooster: false,
// 					condition: 'mv comprenant deux chansons (et non pas deux mvs différents) (cf. heize).',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{
// 					id: 8,
// 					name: "conversion jpn ou chn d'un single kr",
// 					bonusStatus: [AgenciesEnum.XY],
// 					isBooster: false,
// 					condition: "item possible si l'artiste a release la version kr 6 mois auparavant minimum.",
// 					price: 120,
// 					gain: 12,
// 				},
// 				{
// 					id: 9,
// 					name: 'single jpn ou chn',
// 					bonusStatus: [AgenciesEnum.XY],
// 					isBooster: false,
// 					condition: 'chinois, japonais ; palier 7, xingyuan music : palier 5',
// 					price: 180,
// 					gain: 18,
// 				},
// 				{
// 					id: 10,
// 					name: 'single anglais',
// 					isBooster: false,
// 					condition: 'palier 10 minimum. bonus mtp/indé: palier 5.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 11, name: 'featuring', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 12, name: 'collaboration', isBooster: false, condition: '', price: 120, gain: 12 },
// 				{ id: 13, name: 'ost', isBooster: false, condition: '', price: 100, gain: 10 },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROMOTE,
// 			title: 'promotion générale',
// 			description: '',
// 			items: [
// 				{
// 					id: 14,
// 					name: 'expérience',
// 					isBooster: false,
// 					condition: 'achat limité à 10 quantités par mois.',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{ id: 15, name: 'faire une dance practice', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 16,
// 					name: 'photoshoot',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 17,
// 					name: 'couverture de magazine (3★)',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: "l'item doit être cumulé avec l'item photoshoot.",
// 					price: 60,
// 					gain: 6,
// 				},
// 				{ id: 18, name: 'interview magazine', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 19, name: 'interview vidéo (ex. elle)', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 20,
// 					name: 'commercials',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 21,
// 					name: 'bonus égérie: participer à un photoshoot / cf',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 5,
// 				},
// 				{ id: 22, name: "face d'une marque kr (2★)", isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 23, name: "face d'une marque inter (3★)", isBooster: false, condition: '', price: 250, gain: 25 },
// 				{ id: 24, name: "ambassadeur d'une marque kr (3★)", isBooster: false, condition: '', price: 360, gain: 36 },
// 				{
// 					id: 25,
// 					name: "ambassadeur d'une marque internationale (4★)",
// 					isBooster: false,
// 					condition: '',
// 					price: 600,
// 					gain: 60,
// 				},
// 				{ id: 26, name: 'réaliser des campagnes publicitaires', isBooster: false, condition: '', price: 200, gain: 20 },
// 				{
// 					id: 27,
// 					name: 'bonus égérie: post sur les réseaux en partenariat avec une marque',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 4,
// 				},
// 				{
// 					id: 28,
// 					name: "être mc d'une émission",
// 					bonusStatus: [AgenciesEnum.MC],
// 					isBooster: false,
// 					condition: 'avoir obligatoirement le skill variety show & le palier 7.',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 29,
// 					name: "faire partie du casting d'une émission",
// 					isBooster: false,
// 					condition: 'cet item est pour les apparitions à longue durée type sea of hope etc...',
// 					price: 300,
// 					gain: 30,
// 				},
// 				{ id: 30, name: 'apparition dans une émission', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 31,
// 					name: 'bonus skill face: émission',
// 					isBooster: false,
// 					condition: "s'achète EN PLUS de l'item apparition dans une émission.",
// 					price: 0,
// 					gain: 5,
// 				},
// 				{
// 					id: 32,
// 					name: "être mc d'un music show",
// 					isBooster: false,
// 					condition:
// 						"palier 6. pour savoir si une place est libre actuellement, merci d'aller vérifier dans le sujet MY!CUE & GEUMSORI (+ les conditions).",
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 33,
// 					name: 'avoir son talk show (radio)',
// 					isBooster: false,
// 					condition:
// 						'palier 9. cet item s’achète une fois pour le talk show en question. si vous souhaitez y ajouter une nouvelle saison, il faudra acheter l’année suivant l’item nouvelle saison.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 34, name: 'nouvelle saison talk show', isBooster: false, condition: 'palier 9.', price: 120, gain: 12 },
// 				{ id: 35, name: 'participer à un radio show', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{ id: 36, name: 'apparaître dans un m/v', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 37,
// 					name: 'youtube (1 mois)',
// 					isBooster: false,
// 					condition: "ne peut s'acheter qu'après l'achat de l'item youtube (1 mois).",
// 					price: 80,
// 					gain: 8,
// 				},
// 				{ id: 38, name: 'youtube (15jrs)', isBooster: false, condition: '', price: 110, gain: 11 },
// 				{ id: 39, name: 'bonus gnation: poster sur youtube', isBooster: false, condition: '', price: 0, gain: 4 },
// 				{ id: 40, name: 'faire certifier ses réseaux', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{
// 					id: 90,
// 					name: 'performer dans un night club',
// 					isBooster: false,
// 					condition: '',
// 					price: 80,
// 					gain: 8,
// 					specificITem: 0,
// 				},
// 				{ id: 91, name: 'réaliser/participer à un showcase', isBooster: false, condition: '', price: 250, gain: 25 },
// 				{
// 					id: 92,
// 					name: "faire partie de la tournée d'un artiste",
// 					isBooster: false,
// 					condition:
// 						" ton personnage fait partie de la setlist de la tournée d'un artiste ; cet item ne peut être acheté que si l'évènement a vraiment lieu inrp (et que l'artiste est d'accord).",
// 					price: 200,
// 					gain: 20,
// 					specificITem: 0,
// 				},
// 				{
// 					id: 93,
// 					name: "participer à un concert d'artiste",
// 					isBooster: false,
// 					condition:
// 						"ton personnage fait une apparition spéciale le temps d'un concert d'une tournée d'un artiste ; événement en cours + accord de l'artiste nécessaire.",
// 					price: 160,
// 					gain: 16,
// 					specificITem: 0,
// 				},
// 				{
// 					id: 85,
// 					name: 'participer à un festival',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 					specificITem: 0,
// 				},
// 				{ id: 95, name: 'faire du busking', isBooster: false, condition: '', price: 40, gain: 4, specificITem: 0 },
// 				{
// 					id: 96,
// 					name: "booster l'impact d'une chanson",
// 					isBooster: false,
// 					condition: "10 fois pendant l'apparition de la chanson dans les current charts.",
// 					price: 200,
// 					gain: 5000,
// 					specificITem: 0,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.BOOSTER,
// 			title: 'boosters',
// 			description: '',
// 			items: [
// 				{ id: 41, name: 'réaliser des teasers pour son cb', isBooster: true, condition: '', price: 100, gain: 6000 },
// 				{ id: 42, name: 'vlive countdown', isBooster: true, condition: '', price: 300, gain: 18000 },
// 				{
// 					id: 43,
// 					name: 'fans meetings',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu'à 4 fois par cb.",
// 					price: 50,
// 					gain: 300,
// 				},
// 				{ id: 44, name: 'instagram live promotionnel', isBooster: true, condition: '', price: 100, gain: 6000 },
// 				{ id: 45, name: 'showcase', isBooster: true, condition: '', price: 150, gain: 9000 },
// 				{
// 					id: 46,
// 					name: 'promotions (studio choom, relay dance, live…)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 47,
// 					name: 'inscription music show (petit budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes s’inscrivant aux musics shows avec un petit budget ne font, en général, pas les 4 semaines de promotions. sinon, leur temps d’antenne diminue au fil des semaines.',
// 					price: 100,
// 					gain: 6000,
// 				},
// 				{
// 					id: 48,
// 					name: 'inscription music show (gros budget)',
// 					isBooster: true,
// 					condition:
// 						'les artistes avec un gros budget de promotions réalisent leurs 4 semaines et performent l’intégralité des chansons.',
// 					price: 200,
// 					gain: 12000,
// 				},
// 				{
// 					id: 49,
// 					name: 'radio',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 50,
// 					name: 'promotion télévisé (weekly idoles...)',
// 					isBooster: true,
// 					condition: "peut s'acheter jusqu’à 4 fois par cb.",
// 					price: 50,
// 					gain: 3000,
// 				},
// 				{
// 					id: 51,
// 					name: 'affiches promotionnelles station métro/bus',
// 					isBooster: true,
// 					condition: '',
// 					price: 200,
// 					gain: 12000,
// 				},
// 				{
// 					id: 52,
// 					name: 'affiches promotionnelles coex kpop square (2★)',
// 					isBooster: true,
// 					condition: '',
// 					price: 300,
// 					gain: 18000,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: 'Réalisation de projets',
// 			description:
// 				'les items de production sont à prendre occasionnellement (3 fois/mois si lié au projet d’un tier) ; gardez en tête que les idoles n’ont pas beaucoup de temps à consacrer à d’autres productions/réalisations que les leurs. de ce fait, favorisez l’auto-prod.',
// 			items: [
// 				{
// 					id: 53,
// 					name: 'production d’une tt (crédité)',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: 'composition, production, arrangement, paroles, beats.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 54,
// 					name: 'production d’une tt (non crédité)',
// 					isBooster: false,
// 					condition: 'forcément associé à de la co-production, cet item n’apporte du coup pas de streams.',
// 					price: 70,
// 					gain: 7,
// 				},
// 				{
// 					id: 55,
// 					name: 'production d’une b-side',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 70,
// 					gain: 7,
// 				},
// 				{
// 					id: 56,
// 					name: 'production 3 b-sides',
// 					bonusStatus: [AgenciesEnum.MT],
// 					isBooster: false,
// 					condition: '',
// 					price: 210,
// 					gain: 25,
// 				},
// 				{ id: 57, name: 'production d’une ost', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 58,
// 					name: "participer à la chorégraphie d'une émission",
// 					isBooster: false,
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{ id: 59, name: 'chorégraphie', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{ id: 60, name: 'direction artistique', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 61,
// 					name: '2nd rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 62,
// 					name: 'lead rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{
// 					id: 63,
// 					name: '2nd rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 64,
// 					name: 'lead rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 260,
// 					gain: 26,
// 				},
// 				{
// 					id: 65,
// 					name: 'caméo (drama ou film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 80,
// 					gain: 8,
// 				},
// 				{ id: 66, name: 'participer à un masterclass (1jr)', isBooster: false, condition: '', price: 120, gain: 12 },
// 				{
// 					id: 67,
// 					name: 'participer à un séminaire (2 à 3 jrs)',
// 					isBooster: false,
// 					condition: '',
// 					price: 240,
// 					gain: 24,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.GOODIES,
// 			title: ' VENTE DE GOODIES/PROJETS FAN',
// 			description:
// 				'il faut rester réaliste dans l’achat des items suivants. les albums s’achètent uniquement dans le cas d’une release, les albums concerts suite à un concert, season’s greetings une fois par un (au début d’année) etc…',
// 			items: [
// 				{ id: 68, name: 'album physique (simple)', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 69, name: 'album physique (différentes versions)', isBooster: false, condition: '', price: 70, gain: 7 },
// 				{ id: 70, name: 'album physique (members versions)', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 71, name: 'photobook & concert dvd', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 72, name: 'photobook', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 73, name: 'season’s greetings', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 74,
// 					name: 'official fanclub membership',
// 					isBooster: false,
// 					condition: 'achat possible une fois tous les 6 mois.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 75, name: 'lightstick', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 76, name: 'goodies divers', isBooster: false, condition: '', price: 220, gain: 22 },
// 				{ id: 77, name: 'vlive solo', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 78, name: 'vlive groupe', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 79, name: 'vlive anniversaire', isBooster: false, condition: '', price: 200, gain: 20 },
// 				{
// 					id: 80,
// 					name: 'affiches anniversaire',
// 					isBooster: false,
// 					condition:
// 						's’achète pour l’anniversaire de l’artiste, mais également l’anniversaire des débuts de l’artiste.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 81, name: 'coffee event (anniversaire ou cb)', isBooster: false, condition: '', price: 150, gain: 15 },
// 				{ id: 82, name: 'envoi food truck', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{
// 					id: 83,
// 					name: 'organiser un concert (corée)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 				},
// 				{
// 					id: 84,
// 					name: 'organiser un fancon',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 190,
// 					gain: 19,
// 				},
// 				{
// 					id: 85,
// 					name: 'participer à un festival',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition:
// 						"les festivals sont considérés comme une tournée qu'à partir de 5 dates sur un même pays/continent.",
// 					price: 150,
// 					gain: 15,
// 				},
// 				{
// 					id: 86,
// 					name: 'tournée de concerts/festivals (asie)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{
// 					id: 87,
// 					name: 'tournée de concerts/festivals (us & eu)',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: 'palier 7.',
// 					price: 400,
// 					gain: 40,
// 				},
// 				{
// 					id: 88,
// 					name: 'tournée mondiale',
// 					bonusStatus: [AgenciesEnum.HR],
// 					isBooster: false,
// 					condition: 'palier 11.',
// 					price: 600,
// 					gain: 60,
// 				},
// 			],
// 		},
// 	],
// }

// export const DEFAULT_STORE_MODEL: StoreByGroup = {
// 	title: 'Boutique influenceurs, models & sportifs',
// 	id: StoreGroupsEnum.MODEL,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.PROMOTE,
// 			title: 'Promotion générale',
// 			description: '',
// 			items: [
// 				{ id: 14, name: 'expérience', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 37, name: 'youtube (1 mois)', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{
// 					id: 38,
// 					name: 'youtube (15jrs)',
// 					isBooster: false,
// 					condition: "ne peut s'acheter qu'après l'achat de l'item youtube (1 mois).",
// 					price: 120,
// 					gain: 12,
// 				},
// 				{
// 					id: 115,
// 					name: 'youtube (7jrs)',
// 					isBooster: false,
// 					condition: 'achat réservé aux youtubeurs uniquement (hors cover).',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 116,
// 					name: 'publier sur sa chaîne/son compte',
// 					isBooster: false,
// 					bonusStatus: [AgenciesEnum.GN],
// 					condition: 'limité à 4/mois.',
// 					price: 0,
// 					gain: 8,
// 				},
// 				{ id: 40, name: 'faire certifier ses réseaux', isBooster: false, condition: 'palier 3.', price: 140, gain: 14 },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: 'Réalisation de projets',
// 			description: '',
// 			items: [
// 				{ id: 36, name: 'apparaître dans un m/v', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 65,
// 					name: 'caméo (drama ou film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: 'palier 7.',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{ id: 30, name: 'apparition dans une émission', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 28,
// 					name: "être mc d'une émission",
// 					bonusStatus: [AgenciesEnum.MC],
// 					isBooster: false,
// 					condition: 'palier 10.',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 29,
// 					name: "faire partie du casting d'une émission",
// 					isBooster: false,
// 					condition: 'item pour les apparitions à longue durée (ex. sea of hope).',
// 					price: 300,
// 					gain: 30,
// 				},
// 				{
// 					id: 31,
// 					name: 'bonus skill face: émission',
// 					isBooster: false,
// 					condition: "s'achète EN PLUS de l'item apparition dans une émission.",
// 					price: 0,
// 					gain: 5,
// 				},
// 				{
// 					id: 117,
// 					name: 'faire une collab. avec un.e autre influenceur.euse',
// 					isBooster: false,
// 					condition: '',
// 					price: 50,
// 					gain: 5,
// 				},
// 				{
// 					id: 118,
// 					name: 'faire une collab. avec une célébrité',
// 					isBooster: false,
// 					condition: '',
// 					price: 130,
// 					gain: 13,
// 				},
// 				{
// 					id: 119,
// 					name: 'avoir un partenariat rémunéré',
// 					isBooster: false,
// 					condition: 'palier 5.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 120, name: 'communiqué sur une marque/un produit', isBooster: false, condition: '', price: 70, gain: 7 },
// 				{ id: 121, name: 'organiser un concours', isBooster: false, condition: '', price: 40, gain: 4 },
// 				{
// 					id: 16,
// 					name: 'photoshoot',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: 'palier 6 pour les influenceurs purs.',
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 17,
// 					name: 'couverture de magazine (3★)',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: "l'item doit être cumulé avec l'item photoshoot.",
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 20,
// 					name: 'commercials',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: 'palier 6 pour les influenceurs purs.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 21,
// 					name: 'bonus égérie: participer à un photoshoot / cf',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 5,
// 				},
// 				{ id: 18, name: 'interview magazine', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 19, name: 'interview vidéo (ex. elle)', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 26, name: 'réaliser des campagnes publicitaires', isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 22, name: "face d'une marque kr (2★)", isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 23, name: "face d'une marque inter (3★)", isBooster: false, condition: '', price: 250, gain: 25 },
// 				{ id: 24, name: "ambassadeur d'une marque kr (3★)", isBooster: false, condition: '', price: 360, gain: 36 },
// 				{
// 					id: 25,
// 					name: "ambassadeur d'une marque internationale (4★)",
// 					isBooster: false,
// 					condition: '',
// 					price: 600,
// 					gain: 60,
// 				},
// 				{ id: 122, name: 'réaliser/participer à un podcast', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{ id: 35, name: 'participer à un radio show', isBooster: false, condition: '', price: 70, gain: 7 },
// 				{ id: 123, name: 'participer à un mediaday', isBooster: false, condition: '1/mois max.', price: 100, gain: 10 },
// 				{
// 					id: 124,
// 					name: 'participer à un séminaire relation-presse',
// 					isBooster: false,
// 					condition: '',
// 					price: 150,
// 					gain: 15,
// 				},
// 				{ id: 125, name: 'faire un livestream', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 126,
// 					name: 'participer à un tournoi sol coréen',
// 					isBooster: false,
// 					condition: "se baser sur l'irl (k-league).",
// 					price: 250,
// 					gain: 25,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 127,
// 					name: 'participer à un match sol coréen',
// 					isBooster: false,
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 128,
// 					name: 'participer à un tournoi asiatique',
// 					isBooster: false,
// 					condition: "se baser sur l'irl (coupe d'asie).",
// 					price: 450,
// 					gain: 45,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 129,
// 					name: 'participer à un match sol asiatique',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 130,
// 					name: 'participer à un match inter. amical',
// 					isBooster: false,
// 					condition: '',
// 					price: 250,
// 					gain: 25,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 131,
// 					name: 'participer à la coupe du monde',
// 					isBooster: false,
// 					condition: "se baser sur l'irl.",
// 					price: 700,
// 					gain: 70,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 132,
// 					name: 'participer à un match de coupe du monde',
// 					isBooster: false,
// 					condition: '',
// 					price: 450,
// 					gain: 45,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 133,
// 					name: 'signer avec un club coréen',
// 					isBooster: false,
// 					condition: '',
// 					price: 250,
// 					gain: 25,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 134,
// 					name: 'saison dans un club coréen (prêt)',
// 					isBooster: false,
// 					condition: '',
// 					price: 250,
// 					gain: 25,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 135,
// 					name: 'saison dans un club asiatique (prêt)',
// 					isBooster: false,
// 					condition: '',
// 					price: 450,
// 					gain: 45,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 136,
// 					name: 'participer à un entraînement',
// 					isBooster: false,
// 					condition: '',
// 					price: 70,
// 					gain: 7,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 137,
// 					name: "partir en session de training à l'étranger",
// 					isBooster: false,
// 					condition: '',
// 					price: 250,
// 					gain: 25,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 138,
// 					name: 'donner une interview pré-match',
// 					isBooster: false,
// 					condition: '',
// 					price: 90,
// 					gain: 9,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 139,
// 					name: 'donner une interview post-match',
// 					isBooster: false,
// 					condition: '',
// 					price: 120,
// 					gain: 12,
// 					specificITem: 1,
// 				},
// 				{
// 					id: 140,
// 					name: 'être capitaine de son équipe',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 					specificITem: 1,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.BOOSTER,
// 			title: 'BOOSTER SON IMPACT',
// 			description: '',
// 			items: [
// 				{ id: 141, name: "s'acheter des followers", isBooster: false, condition: '', price: 150, gain: 15 },
// 				{
// 					id: 142,
// 					name: 'booster sa visibilité sur les réseaux',
// 					isBooster: false,
// 					condition: '',
// 					price: 170,
// 					gain: 17,
// 				},
// 				{
// 					id: 143,
// 					name: 'être sponsorisé par une marque',
// 					isBooster: false,
// 					condition: 'palier 5. préciser le post en question & la marque.',
// 					price: 190,
// 					gain: 19,
// 				},
// 				{
// 					id: 144,
// 					name: 'faire une vidéo virale sur les réseaux',
// 					isBooster: false,
// 					bonusStatus: [AgenciesEnum.XY],
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 145, name: 'meet-up', isBooster: false, condition: '', price: 100, gain: 10 },
// 				{ id: 72, name: 'photobook', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 73, name: 'season’s greetings', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 74, name: 'official fanclub membership', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{ id: 76, name: 'goodies divers', isBooster: false, condition: '', price: 220, gain: 22 },
// 				{ id: 146, name: 'instagram live', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 80, name: 'affiches anniversaire', isBooster: false, condition: '', price: 240, gain: 24 },
// 				{ id: 192, name: 'coffee event (anniversaire)', isBooster: false, condition: '', price: 150, gain: 15 },
// 				{ id: 82, name: 'envoi food truck', isBooster: false, condition: '', price: 50, gain: 5 },
// 			],
// 		},
// 	],
// }

// export const DEFAULT_STORE_ACTING: StoreByGroup = {
// 	title: 'Boutique acting',
// 	id: StoreGroupsEnum.ACTING,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: "Élaboration d'un projet",
// 			description: '',
// 			items: [
// 				{ id: 103, name: 'participer à une pièce de théâtre', isBooster: false, condition: '', price: 250, gain: 25 },
// 				{
// 					id: 104,
// 					name: 'participer à une comédie musicale',
// 					isBooster: false,
// 					condition: ' skills chant, danse et acting nécessaire.',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{
// 					id: 105,
// 					name: 'caméo (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 106,
// 					name: 'caméo (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: '',
// 					price: 80,
// 					gain: 8,
// 				},
// 				{
// 					id: 61,
// 					name: '2nd rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: 'palier 3.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 63,
// 					name: '2nd rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: 'palier 3.',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 62,
// 					name: 'lead rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: 'palier 5.',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{
// 					id: 64,
// 					name: 'lead rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					isBooster: false,
// 					condition: 'palier 5.',
// 					price: 220,
// 					gain: 22,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROMOTE,
// 			title: 'Promotion générale',
// 			description: '',
// 			items: [
// 				{
// 					id: 14,
// 					name: 'expérience',
// 					isBooster: false,
// 					condition: 'achat limité à 10 quantités par mois.',
// 					price: 100,
// 					gain: 10,
// 				},
// 				{
// 					id: 16,
// 					name: 'photoshoot',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 60,
// 					gain: 6,
// 				},
// 				{
// 					id: 17,
// 					name: 'couverture de magazine (3★)',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: "l'item doit être cumulé avec l'item photoshoot.",
// 					price: 60,
// 					gain: 6,
// 				},
// 				{ id: 18, name: 'interview magazine', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 19, name: 'interview vidéo (ex. elle)', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 20,
// 					name: 'commercials',
// 					bonusStatus: [AgenciesEnum.WM],
// 					isBooster: false,
// 					condition: '',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{
// 					id: 21,
// 					name: 'bonus égérie: participer à un photoshoot / cf',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 5,
// 				},
// 				{ id: 22, name: "face d'une marque kr (2★)", isBooster: false, condition: '', price: 180, gain: 18 },
// 				{ id: 23, name: "face d'une marque inter (3★)", isBooster: false, condition: '', price: 250, gain: 25 },
// 				{ id: 24, name: "ambassadeur d'une marque kr (3★)", isBooster: false, condition: '', price: 360, gain: 36 },
// 				{
// 					id: 25,
// 					name: "ambassadeur d'une marque internationale (4★)",
// 					isBooster: false,
// 					condition: '',
// 					price: 600,
// 					gain: 60,
// 				},
// 				{ id: 26, name: 'réaliser des campagnes publicitaires', isBooster: false, condition: '', price: 200, gain: 20 },
// 				{
// 					id: 27,
// 					name: 'bonus égérie: post sur les réseaux en partenariat avec une marque',
// 					isBooster: false,
// 					condition: '',
// 					price: 0,
// 					gain: 4,
// 				},
// 				{
// 					id: 28,
// 					name: "être mc d'une émission",
// 					bonusStatus: [AgenciesEnum.MC],
// 					isBooster: false,
// 					condition: 'avoir obligatoirement le skill variety show & le palier 7.',
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 29,
// 					name: "faire partie du casting d'une émission",
// 					isBooster: false,
// 					condition: 'cet item est pour les apparitions à longue durée type sea of hope etc...',
// 					price: 300,
// 					gain: 30,
// 				},
// 				{ id: 30, name: 'apparition dans une émission', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 31,
// 					name: 'bonus skill face: émission',
// 					isBooster: false,
// 					condition:
// 						"cet item s'achète EN PLUS de l'item apparition dans une émission et ne peut être acheté que si le personnage a le skill face.",
// 					price: 0,
// 					gain: 5,
// 				},
// 				{
// 					id: 32,
// 					name: "être mc d'un music show",
// 					isBooster: false,
// 					condition:
// 						"palier 6. pour savoir si une place est libre actuellement, merci d'aller vérifier dans le sujet MY!CUE & GEUMSORI (+ les conditions).",
// 					price: 160,
// 					gain: 16,
// 				},
// 				{
// 					id: 33,
// 					name: 'avoir son talk show (radio)',
// 					isBooster: false,
// 					condition:
// 						'palier 9. cet item s’achète une fois pour le talk show en question. si vous souhaitez y ajouter une nouvelle saison, il faudra acheter l’année suivant l’item nouvelle saison.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 34, name: 'nouvelle saison talk show', isBooster: false, condition: 'palier 9.', price: 120, gain: 12 },
// 				{ id: 35, name: 'participer à un radio show', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{ id: 36, name: 'apparaître dans un m/v', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 37, name: 'youtube (1 mois)', isBooster: false, condition: '', price: 80, gain: 8 },
// 				{
// 					id: 38,
// 					name: 'youtube (15jrs)',
// 					isBooster: false,
// 					condition: "ne peut s'acheter qu'après l'achat de l'item youtube (1 mois).",
// 					price: 110,
// 					gain: 11,
// 				},
// 				{ id: 39, name: 'bonus gnation: poster sur youtube', isBooster: false, condition: '', price: 0, gain: 4 },
// 				{ id: 40, name: 'faire certifier ses réseaux', isBooster: false, condition: '', price: 100, gain: 10 },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROMOTE_PROJECT,
// 			title: "Promotion d'un projet",
// 			description: '',
// 			items: [
// 				{ id: 111, name: 'conférence de presse', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{ id: 112, name: 'interview lié à un projet', isBooster: false, condition: '', price: 140, gain: 14 },
// 				{
// 					id: 51,
// 					name: 'affiches promotionnelles station métro/bus',
// 					isBooster: false,
// 					condition: '',
// 					price: 200,
// 					gain: 20,
// 				},
// 				{ id: 52, name: 'affiches promotionnelles coex kpop square (2★)', isBooster: false, price: 300, gain: 30 },
// 				{
// 					id: 113,
// 					name: "licence netflix pour la diffusion d'un drama",
// 					isBooster: false,
// 					condition: '',
// 					price: 500,
// 					gain: 50,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.GOODIES,
// 			title: 'Ventes de goodies/projets fan',
// 			description: '',
// 			items: [
// 				{ id: 72, name: 'photobook', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{ id: 73, name: 'season’s greetings', isBooster: false, condition: '', price: 60, gain: 6 },
// 				{
// 					id: 74,
// 					name: 'official fanclub membership',
// 					isBooster: false,
// 					condition: 'achat possible une fois tous les 6 mois.',
// 					price: 140,
// 					gain: 14,
// 				},
// 				{ id: 114, name: 'dvd drama', isBooster: false, condition: '', price: 120, gain: 12 },
// 				{ id: 76, name: 'goodies divers', isBooster: false, condition: '', price: 220, gain: 22 },
// 				{ id: 77, name: 'vlive solo', isBooster: false, condition: '', price: 50, gain: 5 },
// 				{ id: 79, name: 'vlive anniversaire', isBooster: false, condition: '', price: 200, gain: 20 },
// 				{
// 					id: 80,
// 					name: 'affiches anniversaire',
// 					isBooster: false,
// 					condition: 's’achète pour l’anniversaire de l’artiste.',
// 					price: 240,
// 					gain: 24,
// 				},
// 				{ id: 192, name: 'coffee event (anniversaire)', isBooster: false, condition: '', price: 150, gain: 15 },
// 				{ id: 82, name: 'envoi food truck', isBooster: false, condition: 'préciser l’artiste.', price: 50, gain: 5 },
// 			],
// 		},
// 	],
// }

// export const DEFAULT_STORE_TRAINEES: StoreByGroup = {
// 	title: 'Boutique trainee',
// 	id: StoreGroupsEnum.TRAINEE,
// 	sectionItems: [
// 		{
// 			id: StoreSectionEnum.PROJECT,
// 			title: 'Participation à un projet',
// 			description: '',
// 			items: [
// 				{ id: 36, name: 'apparaître dans un m/v', condition: 'figuration', price: 100, gain: 10, isBooster: false },
// 				{ id: 191, name: 'backdance', condition: '', price: 80, gain: 8, isBooster: false },
// 				{ id: 66, name: 'participer à un masterclass (1jr)', condition: '', price: 150, gain: 15, isBooster: false },
// 				{
// 					id: 67,
// 					name: 'participer à un séminaire (2 à 3 jrs)',
// 					condition: '',
// 					price: 220,
// 					gain: 22,
// 					isBooster: false,
// 				},
// 				{
// 					id: 97,
// 					name: 'participation à un bootcamp (2 à 3 semaines)',
// 					condition: 'ces 3 items peuvent être achetés au maximum 1 fois par mois (et non cumulables).',
// 					price: 300,
// 					gain: 30,
// 					isBooster: false,
// 				},
// 				{ id: 11, name: 'featuring', condition: 'palier 4.', price: 100, gain: 10, isBooster: false },
// 				{ id: 98, name: 'poser sa voix sur une démo', condition: '', price: 500, gain: 50, isBooster: false },
// 				{
// 					id: 65,
// 					name: 'caméo (drama ou film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					condition: '',
// 					price: 100,
// 					gain: 10,
// 					isBooster: false,
// 				},
// 				{
// 					id: 61,
// 					name: '2nd rôle (drama)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					condition: 'palier 3.',
// 					price: 180,
// 					gain: 18,
// 					isBooster: false,
// 				},
// 				{
// 					id: 63,
// 					name: '2nd rôle (film)',
// 					bonusStatus: [AgenciesEnum.A7],
// 					condition: 'palier 3.',
// 					price: 200,
// 					gain: 20,
// 					isBooster: false,
// 				},
// 				{
// 					id: 16,
// 					name: 'photoshoot',
// 					bonusStatus: [AgenciesEnum.WM],
// 					condition: '',
// 					price: 80,
// 					gain: 8,
// 					isBooster: false,
// 				},
// 				{
// 					id: 95,
// 					name: 'faire du busking',
// 					condition:
// 						"spectacle de rue, très fréquent en corée du sud, tout particulièrement dans le quartier d'hongdae",
// 					price: 40,
// 					gain: 4,
// 					isBooster: false,
// 				},
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.CONTENT,
// 			title: 'Élaboration de contenu',
// 			description: '',
// 			items: [
// 				{ id: 14, name: 'expérience', price: 100, gain: 10, isBooster: false },
// 				{ id: 37, name: 'youtube (1 mois)', condition: '', price: 150, gain: 15, isBooster: false },
// 				{ id: 39, name: 'bonus gnation: poster sur youtube', condition: '', price: 0, gain: 4, isBooster: false },
// 				{ id: 99, name: 'ouvrir son insta officiel', condition: '', price: 50, gain: 5, isBooster: false },
// 			],
// 		},
// 		{
// 			id: StoreSectionEnum.PROMOTE_PROJECT,
// 			title: "Promotion d'un projet",
// 			description: '',
// 			items: [
// 				{
// 					id: 100,
// 					name: 'prédebut solo (members intro)',
// 					condition:
// 						'cet achat est uniquement possible dans le cas où vous souhaiteriez introduire vos membres du groupe en solo. ceci ne compte pas comme un début officiel et votre personnage garde son statut de trainee. vous ne pouvez pas choisir un m/v pour cet item.',
// 					price: 250,
// 					gain: 25,
// 					isBooster: false,
// 				},
// 				{
// 					id: 101,
// 					name: 'prédebut single',
// 					condition:
// 						'cet achat est uniquement possible dans le cas où vous souhaiteriez introduire vos membres (ou soliste) via une performance video ou autres (!! pas de mv pour cet item) avant leur début officiel.',
// 					price: 150,
// 					gain: 15,
// 					isBooster: false,
// 				},
// 				{ id: 102, name: 'émission survival pré-debut', condition: '', price: 450, gain: 45, isBooster: false },
// 			],
// 		},
// 	],
// }
